#!/usr/bin/env python3
"""Generates every per-tenant config block from infra/tenants.yaml.

One tenant costs an exporter and a pipeline per routed signal, a runtime-overrides
entry in each of three backends, and an entry in every Grafana datasource's
federation list. That is ~10 blocks across 5 files for one line of intent, and
every way of getting it wrong is silent: telemetry lands in the catch-all, or a
limit is never applied, and nothing reports either.

Run: python3 scripts/gen-tenants.py       (writes)
     python3 scripts/gen-tenants.py --check  (exits 1 if output would change)

WHY THIS ONE USES PyYAML AND check-compat.py DOES NOT
check-compat.py regexes the collector config because it only asserts a handful
of values inside a file a human maintains. This reads a structured manifest and
must understand nesting, defaults and absence. Regexing that would be a parser
with no error messages. The manifest has to stay YAML rather than JSON because
its comments are the documentation for what a tenant costs.

WHAT THIS DELIBERATELY DOES NOT GENERATE
config.platform.yaml itself. That file is mostly load-bearing prose - the
comments ARE the platform's operational documentation - and a generator would
either destroy them or carry them as Python string literals. This emits a
fragment instead, merged by a second --config flag. Collector configs merge maps
recursively but REPLACE lists, so no YAML list may be defined in both files.
"""
import pathlib
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "infra/tenants.yaml"

# Loki's tenant-ID rule (pkg/util/http.go): alphanumerics plus ! - _ . * ' ( ),
# at most 150 bytes, and neither "." nor "..". Enforced HERE because Loki
# enforces it at write time, in the distributor - a bad name config-loads
# cleanly and then silently rejects every log line that tenant sends.
TENANT_RE = re.compile(r"^[A-Za-z0-9!\-_.*'()]+$")

BANNER = (
    "# GENERATED by scripts/gen-tenants.py from infra/tenants.yaml - DO NOT EDIT.\n"
    "# Edit the manifest and re-run the generator; CI fails if the two disagree."
)


def die(msg):
    sys.exit(f"gen-tenants: {msg}")


def load():
    doc = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    tenants = doc["tenants"]
    defaults = doc["defaults"]
    budget = doc["budget"]

    seen = set()
    catch_alls = [t for t in tenants if t.get("catch_all")]
    if len(catch_alls) != 1:
        die(f"exactly one tenant must set catch_all: true, found {len(catch_alls)}")

    for t in tenants:
        name = t["name"]
        if not TENANT_RE.match(name) or name in (".", "..") or len(name.encode()) > 150:
            die(
                f"tenant name {name!r} is not a valid Loki tenant id. "
                "Allowed: letters, digits and ! - _ . * ' ( ), max 150 bytes, "
                "not '.' or '..'. Loki rejects invalid ids at write time, not "
                "at config load, so this would ship as silent data loss."
            )
        if name in seen:
            die(f"duplicate tenant {name!r}")
        seen.add(name)

    # Budget. A limit that is quietly oversubscribed is how a platform OOMs
    # weeks after the change that caused it, so this is a hard failure.
    total = sum(limit(t, defaults, "mimir", "max_global_series_per_user") for t in tenants)
    cap = budget["mimir_total_series"]
    if total > cap:
        die(
            f"per-tenant series caps sum to {total:,}, over the {cap:,} budget.\n"
            f"  Mimir holds ~150k series in its 2 GiB limit. Adding this tenant needs\n"
            f"  either a lower default, a lower cap on another tenant, or more RAM -\n"
            f"  it is a decision about the box, not a number to nudge."
        )

    gen_total = sum(
        limit(t, defaults, "tempo", "metrics_generator_max_active_series") for t in tenants
    )
    gen_cap = int(cap * budget["tempo_generator_series_ratio"])
    if gen_total > gen_cap:
        die(f"tempo generator series sum to {gen_total:,}, over the {gen_cap:,} budget")

    return doc, tenants, defaults, budget, total


def limit(tenant, defaults, backend, key):
    """A tenant's effective limit: its own override, else the manifest default."""
    return tenant.get("limits", {}).get(backend, {}).get(key, defaults[backend][key])


def routed(tenants):
    """Tenants whose telemetry is matched by the routing table, in manifest order."""
    return [t for t in tenants if t.get("routed", True) and not t.get("catch_all")]


def catch_all(tenants):
    return next(t for t in tenants if t.get("catch_all"))


# --- collector fragment -------------------------------------------------------

def collector_fragment(tenants):
    """Per-tenant exporters, the routing connectors, and the pipelines they feed.

    Traces are deliberately NOT routed. Tempo's metrics generator pairs spans
    within one trace within one tenant, so splitting a cross-team trace across
    two Tempo tenants means the service-graph edge between those teams is never
    produced - and federation cannot recover a metric that was never written.
    Blast Radius is built on exactly that edge.
    """
    ca = catch_all(tenants)["name"]
    # Exporters that a generated pipeline actually references. Queue sizes are
    # budgeted so N exporters together hold roughly what the single exporter
    # held before: the defaults are PER INSTANCE (otlphttp 10 consumers x 1000
    # requests, prw 10000 items x 5), and N of those is the real memory risk -
    # not the exporter count itself. The failure mode is a backend restart:
    # untuned, memory_limiter starts refusing at the receiver and every tenant
    # loses data because one backend was slow.
    metric_tenants = [t["name"] for t in tenants]
    log_tenants = [t["name"] for t in routed(tenants)] + [ca]

    prw_queue = max(500, 10000 // max(1, len(metric_tenants)))
    log_queue = max(50, 1000 // max(1, len(log_tenants)))

    out = [BANNER, "\nexporters:"]
    for name in metric_tenants:
        out.append(f"""  prometheus_remote_write/{name}:
    endpoint: http://mimir:9009/api/v1/push
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: {name}
    resource_to_telemetry_conversion:
      enabled: true
    remote_write_queue:
      queue_size: {prw_queue}
      num_consumers: 1""")
    for name in log_tenants:
        out.append(f"""  otlp_http/logs_{name}:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: {name}
    sending_queue:
      queue_size: {log_queue}
      num_consumers: 2""")

    # One connector instance per signal: a connector only resolves pipelines of
    # its own signal type, so a single `routing:` block whose table names
    # metrics pipelines cannot also serve logs.
    out.append("\nconnectors:")
    for signal in ("metrics", "logs"):
        out.append(f"""  routing/{signal}:
    # `propagate` (the default) DROPS the payload when a condition errors. On a
    # platform whose premise is that nothing is ever discarded silently, the
    # default is the wrong choice: `ignore` sends it to the catch-all instead.
    error_mode: ignore
    default_pipelines: [{signal}/t-{ca}]
    table:""")
        for t in routed(tenants):
            name = t["name"]
            pattern = "|".join(
                re.escape(a) for a in [name] + list(t.get("aliases", []))
            )
            # Case-insensitive because the realistic failure is `team=Gudangsolusi`
            # landing in the catch-all invisibly, not a wholly wrong value.
            out.append(f"""      - context: resource
        condition: IsMatch(attributes["team"], "^(?i)({pattern})$")
        pipelines: [{signal}/t-{name}]""")

    out.append("\nservice:\n  pipelines:")
    for name in metric_tenants:
        if name in [t["name"] for t in routed(tenants)] + [ca]:
            out.append(f"""    metrics/t-{name}:
      receivers: [routing/metrics]
      exporters: [prometheus_remote_write/{name}]""")
    for name in log_tenants:
        out.append(f"""    logs/t-{name}:
      receivers: [routing/logs]
      exporters: [otlp_http/logs_{name}]""")

    return "\n".join(out) + "\n"


# --- backend runtime overrides ------------------------------------------------

def mimir_runtime(tenants, defaults):
    """Hot-reloaded every 10s; no restart. Loader is STRICT - an unknown key is
    a hard load failure, which is why only known keys are emitted here.

    Every tenant gets an explicit entry even when it equals the default, because
    the overrides-exporter emits cortex_limits_overrides ONLY for tenants with an
    explicit entry. A tenant on defaults would show as a gap on the per-tenant
    dashboard rather than as a tenant at its default.
    """
    out = [BANNER, "\noverrides:"]
    for t in tenants:
        name = t["name"]
        out.append(f"""  {name}:
    max_global_series_per_user: {limit(t, defaults, 'mimir', 'max_global_series_per_user')}
    max_global_exemplars_per_user: {limit(t, defaults, 'mimir', 'max_global_exemplars_per_user')}""")
    return "\n".join(out) + "\n"


def loki_runtime(tenants, defaults):
    out = [BANNER, "\noverrides:"]
    for t in tenants:
        name = t["name"]
        out.append(f"""  {name}:
    max_global_streams_per_user: {limit(t, defaults, 'loki', 'max_global_streams_per_user')}
    ingestion_rate_mb: {limit(t, defaults, 'loki', 'ingestion_rate_mb')}""")
    return "\n".join(out) + "\n"


def tempo_overrides(tenants, defaults):
    """Traces are not routed, so in practice only the catch-all tenant receives
    spans today. The per-tenant entries are still emitted so that enabling trace
    routing later is a manifest change and not a new file.
    """
    out = [BANNER, "\noverrides:"]
    for t in tenants:
        name = t["name"]
        out.append(f"""  {name}:
    ingestion:
      rate_limit_bytes: {limit(t, defaults, 'tempo', 'ingestion_rate_limit_bytes')}
      max_traces_per_user: {limit(t, defaults, 'tempo', 'ingestion_max_traces_per_user')}
    metrics_generator:
      max_active_series: {limit(t, defaults, 'tempo', 'metrics_generator_max_active_series')}""")
    return "\n".join(out) + "\n"


# --- operator summary ---------------------------------------------------------

def summary(tenants, defaults, budget, total):
    """The federation header values and the budget, in a form an operator reads.

    Legacy ids differ per backend because each store names its single-tenant
    bucket differently, and they must stay in the read lists until data written
    before the cutover ages out (7d logs/traces, 30d metrics).
    """
    names = [t["name"] for t in tenants]
    legacy = {"prometheus": "anonymous", "loki": "fake", "tempo": "single-tenant"}
    # The pipe is the tenant separator AND the markdown cell separator, so it
    # has to be escaped or the table renders as one mangled column.
    rows = "\n".join(
        "| `{}` | `{}` |".format(ds, "\\|".join(names + [lg]))
        for ds, lg in legacy.items()
    )
    caps = "\n".join(
        f"| `{t['name']}` | {limit(t, defaults, 'mimir', 'max_global_series_per_user'):,} "
        f"| {limit(t, defaults, 'tempo', 'metrics_generator_max_active_series'):,} "
        f"| {'catch-all' if t.get('catch_all') else ('routed' if t.get('routed', True) else 'pipeline-assigned')} |"
        for t in tenants
    )
    return f"""<!-- {BANNER.strip().splitlines()[0][2:]} -->
# Tenants

Generated from [tenants.yaml](tenants.yaml). Do not edit.

## Series budget

**{total:,} of {budget['mimir_total_series']:,}** allocated, {budget['mimir_total_series'] - total:,} free.
Adding a tenant past the budget fails the generator rather than oversubscribing
the box — Mimir holds roughly 150k active series inside its 2 GiB limit.

| Tenant | Mimir series | Tempo generator series | Routing |
|---|---|---|---|
{caps}

## Grafana datasource federation

Each datasource sends `X-Scope-OrgID` with every tenant it may read, plus the
legacy single-tenant id for data written before the cutover. The lists differ
because each backend names its pre-tenancy bucket differently.

| Datasource uid | `httpHeaderValue1` |
|---|---|
{rows}

Loki live-tail (`/loki/api/v1/tail`) returns **HTTP 400** when more than one
tenant is in the header, so Grafana Explore's Live button needs a separate
single-tenant `loki-tail` datasource.
"""


TARGETS = {
    "infra/otel-collector/tenants.platform.yaml": collector_fragment,
    "infra/mimir/runtime.yaml": mimir_runtime,
    "infra/loki/runtime.yaml": loki_runtime,
    "infra/tempo/overrides.yaml": tempo_overrides,
    "infra/TENANTS.md": summary,
}


def render(tenants, defaults, budget, total):
    return {
        "infra/otel-collector/tenants.platform.yaml": collector_fragment(tenants),
        "infra/mimir/runtime.yaml": mimir_runtime(tenants, defaults),
        "infra/loki/runtime.yaml": loki_runtime(tenants, defaults),
        "infra/tempo/overrides.yaml": tempo_overrides(tenants, defaults),
        "infra/TENANTS.md": summary(tenants, defaults, budget, total),
    }


if __name__ == "__main__":
    check = "--check" in sys.argv
    _doc, tenants, defaults, budget, total = load()
    stale = []
    for rel, body in render(tenants, defaults, budget, total).items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == body:
            continue
        if check:
            stale.append(rel)
        else:
            path.write_text(body, encoding="utf-8", newline="\n")
            print(f"  wrote {rel}")
    if check and stale:
        sys.exit(
            "gen-tenants: these are out of date with infra/tenants.yaml:\n"
            + "".join(f"  {s}\n" for s in stale)
            + "Run: python3 scripts/gen-tenants.py"
        )
    if check:
        print(f"generated tenant config matches the manifest ({len(tenants)} tenants)")
    else:
        print(f"{len(tenants)} tenants, {total:,}/{budget['mimir_total_series']:,} series allocated")
