import { readFileSync } from 'node:fs';

/**
 * The teams a submitter may pick, read from infra/teams.json.
 *
 * That file is generated by scripts/gen-tenants.py from infra/tenants.yaml and
 * bind-mounted in. It is not parsed from the YAML here on purpose: no YAML
 * parser exists in this service (express is its only dependency), and the
 * filter is subtler than it looks — `routed` is absent-means-true, and
 * `platform`/`unattributed` are tenants but not teams. That logic lives in the
 * generator; duplicating it in another language is how the two drift.
 */
export interface Team {
  name: string;
  description: string;
}

export interface TeamList {
  teams: Team[];
  /** The tenant unrouted telemetry lands in. Never offered as a pickable team. */
  catchAll: string;
  /** False when the file was missing or unreadable — the form must say so. */
  available: boolean;
}

const EMPTY: TeamList = { teams: [], catchAll: 'unattributed', available: false };

/**
 * Parses the generated file. Separate from the I/O so it can be tested without
 * a filesystem, which is the idiom the rest of this service uses.
 *
 * Anything malformed yields the empty list rather than throwing. A submitter
 * being shown no teams is recoverable — they pick "not listed" and land in the
 * catch-all, which is the right answer when the platform's team list is
 * unknown. The API refusing to start is not recoverable.
 */
export function parseTeams(text: string): TeamList {
  try {
    const doc = JSON.parse(text) as Partial<TeamList>;
    const teams = Array.isArray(doc.teams)
      ? doc.teams
          .filter((t): t is Team => Boolean(t) && typeof t.name === 'string' && t.name !== '')
          .map((t) => ({ name: t.name, description: String(t.description ?? '') }))
      : [];
    return {
      teams,
      catchAll: typeof doc.catchAll === 'string' && doc.catchAll ? doc.catchAll : EMPTY.catchAll,
      available: true,
    };
  } catch {
    return { ...EMPTY };
  }
}

/**
 * Reads the list once, at startup.
 *
 * Deliberately loud on failure. A missing mount degrades to "no teams
 * selectable", which is safe but silently routes every onboarding into the
 * shared catch-all pool — exactly the condition the platform's catch-all alert
 * exists to flag. Whoever deployed it should find out from the log, not from a
 * dashboard a week later.
 */
export function loadTeams(path: string | undefined): TeamList {
  if (!path) {
    console.warn(
      '[onboarding-agent] TEAMS_FILE is not set. The form will offer no teams and ' +
        'every onboarding will land in the catch-all tenant.',
    );
    return { ...EMPTY };
  }
  try {
    const list = parseTeams(readFileSync(path, 'utf8'));
    if (!list.available || list.teams.length === 0) {
      console.warn(
        `[onboarding-agent] ${path} parsed but lists no teams. Check that ` +
          'scripts/gen-tenants.py has been run and the file is mounted.',
      );
    } else {
      console.log(
        `[onboarding-agent] ${list.teams.length} team(s) available: ` +
          list.teams.map((t) => t.name).join(', '),
      );
    }
    return list;
  } catch (err) {
    console.warn(
      `[onboarding-agent] could not read ${path} (${(err as Error).message}). ` +
        'The form will offer no teams and every onboarding will land in the ' +
        'catch-all tenant. Is infra/teams.json mounted?',
    );
    return { ...EMPTY };
  }
}

/**
 * Whether a submitted team may be used.
 *
 * Enforced server-side, not just by the dropdown. A `<select>` is a convention
 * a curl request ignores, and this is the one input that silently misroutes a
 * service's entire telemetry: an unrecognised team is not rejected by the
 * platform, it is accepted into the shared catch-all and looks correct in
 * Grafana. Better to refuse it here, where the valid names can be named.
 *
 * An absent team stays absent — that is the explicit "not listed" choice.
 */
export function isKnownTeam(list: TeamList, team: string): boolean {
  return list.teams.some((t) => t.name === team);
}
